<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('items')->insert(['name' => 'Café americano', 'price' => '82.76', 'description' => 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', 'image' => 'nan', 'stock' => '143', 'Item_type_id' => '18']);
        DB::table('items')->insert(['name' => 'Capuchino', 'price' => '494.18', 'description' => 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui', 'image' => 'nan', 'stock' => '147', 'Item_type_id' => '23']);
        DB::table('items')->insert(['name' => 'Latte', 'price' => '269.38', 'description' => 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus', 'image' => 'nan', 'stock' => '149', 'Item_type_id' => '22']);
        DB::table('items')->insert(['name' => 'Té', 'price' => '369.46', 'description' => 'mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 'image' => 'nan', 'stock' => '74', 'Item_type_id' => '29']);
        DB::table('items')->insert(['name' => 'Galletas', 'price' => '144.56', 'description' => 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 'image' => 'nan', 'stock' => '42', 'Item_type_id' => '13']);
        DB::table('items')->insert(['name' => 'Pasteles', 'price' => '418.21', 'description' => 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et', 'image' => 'nan', 'stock' => '55', 'Item_type_id' => '1']);
        DB::table('items')->insert(['name' => 'Sándwiches', 'price' => '281.42', 'description' => 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum', 'image' => 'nan', 'stock' => '77', 'Item_type_id' => '18']);
        DB::table('items')->insert(['name' => 'Bagels', 'price' => '333.25', 'description' => 'ut nulla sed accumsan felis ut at dolor quis odio consequat', 'image' => 'nan', 'stock' => '21', 'Item_type_id' => '6']);
        DB::table('items')->insert(['name' => 'Donas', 'price' => '169.29', 'description' => 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna', 'image' => 'nan', 'stock' => '89', 'Item_type_id' => '10']);
        DB::table('items')->insert(['name' => 'Ensaladas', 'price' => '125.36', 'description' => 'massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', 'image' => 'nan', 'stock' => '141', 'Item_type_id' => '3']);
        DB::table('items')->insert(['name' => 'Jugos naturales', 'price' => '429.17', 'description' => 'venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 'image' => 'nan', 'stock' => '30', 'Item_type_id' => '24']);
        DB::table('items')->insert(['name' => 'Batidos', 'price' => '347.15', 'description' => 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 'image' => 'nan', 'stock' => '57', 'Item_type_id' => '19']);
        DB::table('items')->insert(['name' => 'Smoothies', 'price' => '235.83', 'description' => 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', 'image' => 'nan', 'stock' => '82', 'Item_type_id' => '3']);
        DB::table('items')->insert(['name' => 'Wraps', 'price' => '239.9', 'description' => 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', 'image' => 'nan', 'stock' => '141', 'Item_type_id' => '28']);
        DB::table('items')->insert(['name' => 'Yogur', 'price' => '291.76', 'description' => 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam', 'image' => 'nan', 'stock' => '33', 'Item_type_id' => '15']);
        DB::table('items')->insert(['name' => 'Frutas', 'price' => '402.92', 'description' => 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien', 'image' => 'nan', 'stock' => '30', 'Item_type_id' => '13']);
        DB::table('items')->insert(['name' => 'Aguas frescas', 'price' => '309.0', 'description' => 'est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit', 'image' => 'nan', 'stock' => '26', 'Item_type_id' => '27']);
        DB::table('items')->insert(['name' => 'Chocolates calientes', 'price' => '406.3', 'description' => 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 'image' => 'nan', 'stock' => '14', 'Item_type_id' => '28']);
        DB::table('items')->insert(['name' => 'Tostadas francesas', 'price' => '367.5', 'description' => 'interdum in ante vestibulum ante ipsum primis in faucibus orci', 'image' => 'nan', 'stock' => '22', 'Item_type_id' => '12']);
        DB::table('items')->insert(['name' => 'Huevos revueltos', 'price' => '378.74', 'description' => 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 'image' => 'nan', 'stock' => '118', 'Item_type_id' => '30']);
        DB::table('items')->insert(['name' => 'Chilaquiles', 'price' => '193.78', 'description' => 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', 'image' => 'nan', 'stock' => '32', 'Item_type_id' => '24']);
        DB::table('items')->insert(['name' => 'Hotcakes', 'price' => '80.01', 'description' => 'suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla', 'image' => 'nan', 'stock' => '25', 'Item_type_id' => '28']);
        DB::table('items')->insert(['name' => 'Waffles', 'price' => '119.64', 'description' => 'tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper', 'image' => 'nan', 'stock' => '54', 'Item_type_id' => '6']);
        DB::table('items')->insert(['name' => 'Omelettes', 'price' => '486.52', 'description' => 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 'image' => 'nan', 'stock' => '103', 'Item_type_id' => '21']);
        DB::table('items')->insert(['name' => 'Croissants', 'price' => '344.07', 'description' => 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 'image' => 'nan', 'stock' => '97', 'Item_type_id' => '15']);
        DB::table('items')->insert(['name' => 'Panini', 'price' => '54.37', 'description' => 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi', 'image' => 'nan', 'stock' => '77', 'Item_type_id' => '27']);
        DB::table('items')->insert(['name' => 'Pan dulce', 'price' => '338.26', 'description' => 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 'image' => 'nan', 'stock' => '140', 'Item_type_id' => '3']);
        DB::table('items')->insert(['name' => 'Nachos', 'price' => '320.61', 'description' => 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 'image' => 'nan', 'stock' => '116', 'Item_type_id' => '15']);
        DB::table('items')->insert(['name' => 'Papas a la francesa', 'price' => '477.19', 'description' => 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel', 'image' => 'nan', 'stock' => '150', 'Item_type_id' => '22']);
        DB::table('items')->insert(['name' => 'Nuggets de pollo', 'price' => '369.5', 'description' => 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'image' => 'nan', 'stock' => '52', 'Item_type_id' => '18']);
        DB::table('items')->insert(['name' => 'Hot dogs', 'price' => '402.4', 'description' => 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 'image' => 'nan', 'stock' => '43', 'Item_type_id' => '26']);
        DB::table('items')->insert(['name' => 'Hamburguesas', 'price' => '404.43', 'description' => 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', 'image' => 'nan', 'stock' => '103', 'Item_type_id' => '24']);
        DB::table('items')->insert(['name' => 'Pizza', 'price' => '198.99', 'description' => 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero', 'image' => 'nan', 'stock' => '68', 'Item_type_id' => '3']);
        DB::table('items')->insert(['name' => 'Pita', 'price' => '64.38', 'description' => 'risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 'image' => 'nan', 'stock' => '62', 'Item_type_id' => '19']);
        DB::table('items')->insert(['name' => 'Panini', 'price' => '82.27', 'description' => 'convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', 'image' => 'nan', 'stock' => '136', 'Item_type_id' => '13']);
        DB::table('items')->insert(['name' => 'Fajitas', 'price' => '227.54', 'description' => 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', 'image' => 'nan', 'stock' => '8', 'Item_type_id' => '8']);
        DB::table('items')->insert(['name' => 'Burritos', 'price' => '168.71', 'description' => 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 'image' => 'nan', 'stock' => '37', 'Item_type_id' => '10']);
        DB::table('items')->insert(['name' => 'Tacos', 'price' => '300.61', 'description' => 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', 'image' => 'nan', 'stock' => '92', 'Item_type_id' => '23']);
        DB::table('items')->insert(['name' => 'Sopa', 'price' => '214.88', 'description' => 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris', 'image' => 'nan', 'stock' => '46', 'Item_type_id' => '3']);
        DB::table('items')->insert(['name' => 'Ceviche', 'price' => '302.21', 'description' => 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in', 'image' => 'nan', 'stock' => '113', 'Item_type_id' => '9']);
        DB::table('items')->insert(['name' => 'Enchiladas', 'price' => '131.62', 'description' => 'nisl aenean lectus pellentesque eget nunc donec quis orci eget', 'image' => 'nan', 'stock' => '150', 'Item_type_id' => '28']);
        DB::table('items')->insert(['name' => 'Pambazos', 'price' => '353.1', 'description' => 'volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 'image' => 'nan', 'stock' => '29', 'Item_type_id' => '9']);
        DB::table('items')->insert(['name' => 'Chiles rellenos', 'price' => '235.32', 'description' => 'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 'image' => 'nan', 'stock' => '126', 'Item_type_id' => '28']);
        DB::table('items')->insert(['name' => 'Quesadillas', 'price' => '228.95', 'description' => 'nulla nunc purus phasellus in felis donec semper sapien a libero', 'image' => 'nan', 'stock' => '111', 'Item_type_id' => '15']);
        DB::table('items')->insert(['name' => 'Papel bond', 'price' => '263.03', 'description' => 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus', 'image' => 'nan', 'stock' => '52', 'Item_type_id' => '5']);
        DB::table('items')->insert(['name' => 'Carpetas', 'price' => '437.43', 'description' => 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere', 'image' => 'nan', 'stock' => '13', 'Item_type_id' => '14']);
        DB::table('items')->insert(['name' => 'Cuadernos', 'price' => '361.55', 'description' => 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante', 'image' => 'nan', 'stock' => '48', 'Item_type_id' => '16']);
        DB::table('items')->insert(['name' => 'Lapiceros', 'price' => '437.18', 'description' => 'id turpis integer aliquet massa id lobortis convallis tortor risus', 'image' => 'nan', 'stock' => '147', 'Item_type_id' => '3']);
        DB::table('items')->insert(['name' => 'Bolígrafos', 'price' => '129.64', 'description' => 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', 'image' => 'nan', 'stock' => '133', 'Item_type_id' => '14']);
        DB::table('items')->insert(['name' => 'Marcadores', 'price' => '236.74', 'description' => 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel', 'image' => 'nan', 'stock' => '144', 'Item_type_id' => '21']);
    }
}
